[project]
name = "ai-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "grpcio>=1.75.1",
    "grpcio-tools>=1.75.1",
    "numpy>=2.2.6",
]
